services:
  todo:
    build: ./
    volumes:
      - .:/todo
    ports:
      - 8002:8000
  mysql:
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=dev
      - MYSQL_ROOT_PASSWORD=password

volumes:
  mysql:
    